title: (10 piece) Puzzler
author: Florent Biville
description: Insatiable Learner
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fbiville.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fbiville
github_username:  fbiville

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
