= Pourquoi venir au Hackergarten

Qu'on se le dise, les logiciels Open Source sont partout.
Il y a fort à parier que vous les utilisiez directement 
voire en développiez dans votre activité professionnelle. 
Il demeure indéniable que vous en bénéficiez dans votre 
vie quotidienne, même indirectement. 


== Hackers: we need you!

Il vous est peut-être même arrivé de renseigner un bug, 
voire de soumettre un correctif à un logiciel open-source 
que vous utilisez dans le cadre professionnel. Mais en 
dehors de ces rares occasions, vous n'avez jamais trouvé 
le temps de contribuer de façon plus pérenne.

Pourtant, en voilà un objectif qui peut rendre fier|fière !
Devenir l'un des committers principaux d'un projet visible
(ou en passe de le devenir) peut faire une belle différence 
sur le CV et dans votre carrière.

Cela ne se fait évidemment pas en un jour, mais chaque 
première contribution est importante. Il peut être assez
difficile de se plonger dans une base de code inconnue
sans aide extérieure, ni objectif précis.

Paris Hackergarten est là pour vous !

Il vise à regrouper, dans une même pièce, le temps d'une
soirée (1 fois par mois), committers confirmés (a.k.a. mentors) 
et contributeurs motivés (a.k.a. hackers) !

Chacun y retrouve son compte :

 - le mentor voit son projet avancer grâce aux contributions
 - le hacker se familiarise avec la base de code, avec l'aide 
 du mentor et envoie ses premières contributions en quelques 
 heures, et non pas en quelques jours

Lors de la dernière soirée, un binôme a réussi à soumettre 
une évolution au projet Apache Maven ! Ils ont pourtant
commencé la soirée sans connaissances préalables de la base 
de code. 

Tous les hackers sont bienvenus ! Ne vous auto-censurez pas
en pensant que vous n'avez pas le niveau, ça n'est pas vrai ! ;-)

Nous avons la chance d'avoir Hervé Boutémy parmi les mentors, 
committer Maven, qui se rend disponible à chaque session 
pour aiguiller les hackers et ainsi leur permettre de faire 
avancer le projet.

== Appel aux mentors

Vous souhaitez présenter votre projet et attirer de nouvelles
contributions ?

Pour se faire, deux règles sont en vigueur :

 1. préparer une présentation deux minutes afin de familiariser
 et "vendre" votre projet aux participants
 2. avoir un ensemble de tâches bien définies, idéalement 
 réalisables en une soirée

Concernant la technologie employée : aucune contrainte !

Je tiens à insister sur ce point. On pourrait croire 
actuellement que le meetup est réservé aux développeurs Java, 
ça n'est pas le cas !

Il se peut même qu'une session du Paris Hackergarten soit 
prochainement dédiée au développement iOS, stay tuned! ;-)

== À vos calendriers !

Nous nous efforçons d'organiser le http://www.meetup.com/Paris-Hackergarten/[Paris Hackergarten] tous les derniers mardis du mois, dans les locaux de Xebia.

Le prochain aura donc lieu le 27 Septembre, j'espère donc vous y voir !